#!/usr/bin/env python3

from pypresence import Presence
from pypresence.types import ActivityType, StatusDisplayType
import time, argparse, rumps

# CLI arguments
arguments = argparse.ArgumentParser()
arguments.add_argument("--name")
arguments.add_argument("--interval", type=int, default=0)
arguments.add_argument("--duration", type=int, default=0)
arguments.add_argument("--playing", action="store_true")
arguments.add_argument("--listening", action="store_true")

args = arguments.parse_args()

interval = args.interval
duration = args.duration*60
focusName = args.name
isPlaying = args.playing
isListening = args.listening

if isListening:
    layoutType = ActivityType.LISTENING
if isPlaying:
    layoutType = ActivityType.PLAYING

client_id = "1484792781976113253"
RPC = Presence(client_id)
RPC.connect()

# If one of the arguments is missing, ask for input 
if focusName == None:
    focusName = input("What is the name of this focus session? ")
if interval == 0 or duration == 0:
    interval = int(input("\nHow many intervals? (1-20) "))
    duration = int(input("\nHow long for each interval? (in minutes) (1-90) "))*60
if not isPlaying and not isListening:
    print("\nChoose your preferred presence style:")
    print("1. Listening (with progress bar)")
    print("Notice: It is not recommended to start this presence when another music presence is running, as it will not display as the main status.")
    print("2. Playing (classic style)")
    print("Notice: Only use this if you do not have any game presences running.")
    selection = int(input("\n→ Option: "))
    match selection:
        case 1:
            layoutType = ActivityType.LISTENING
        case 2:
            layoutType = ActivityType.PLAYING

print("Running...")

# Update the rich presence during focus sessions
def focus(intervalCount, start, current):
    RPC.update(
        activity_type=layoutType,
        status_display_type=StatusDisplayType.DETAILS,
        state="Lock in!", 
        details=f"{focusName} ({intervalCount+1}/{interval})",
        start = start,
        end = start+current,
        large_image="pomodoro"
    )

# Update the rich presence during break sessions
def rest(start, current):
    RPC.update(
        activity_type=layoutType,
        status_display_type=StatusDisplayType.DETAILS,
        state="¯\\_(ツ)_/¯", 
        details="Resting",
        start = start,
        end = start+current,
        large_image="pomodoro"
    )
    
# Menu bar feature that also triggers Discord Rich Presence using the rumps library.
# The logic of rumps is generated by ChatGPT.

class Premodoro(rumps.App):
    def __init__(self):
        super().__init__("Starting")
        self.intervalCounter = 0
        self.counter = 0
        self.status = ""
        self.is_break = False
        self.start = int(time.time())
        self.current_duration = duration
        self.timer = rumps.Timer(self.update_timer, 1)
        self.timer.start()

    def reconnect_rpc(self):
        global RPC

        while True:
            try:
                time.sleep(3)
                RPC = Presence(client_id)
                RPC.connect()
                return
            except Exception:
                pass

    def update_timer(self, sender):
        global RPC

        try:
            self.status = f"{self.intervalCounter + 1}/{interval}"
            if self.counter >= self.current_duration:
                if self.is_break:
                    if self.intervalCounter >= interval:
                        self.timer.stop()
                        rumps.quit_application()
                        return

                    self.is_break = False
                    self.counter = 0
                    self.current_duration = duration
                    self.start = int(time.time())

                else:
                    self.intervalCounter += 1
                    self.is_break = True
                    self.counter = 0

                    if self.intervalCounter % 4 == 0:
                        self.current_duration = round(duration * 0.2 * 2.5)
                    else:
                        self.current_duration = round(duration * 0.2)

                    self.start = int(time.time())

            remaining = self.current_duration - self.counter
            mins = remaining // 60
            secs = remaining % 60
            
            if self.is_break:
                self.title = f"[{focusName}] {mins:02}:{secs:02} | Resting"
                rest(self.start, self.current_duration)
            else:
                self.title = f"[{focusName}] {mins:02}:{secs:02} | {self.intervalCounter + 1}/{interval}"
                focus(self.intervalCounter, self.start, self.current_duration)

            self.counter += 1

        except Exception as e:
            print(e)
            self.reconnect_rpc()

if __name__ == "__main__":
    Premodoro().run()